apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-app-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-app-back
  template:
    metadata:
      labels:
        app: mall-app-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: mall-app-back
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: mall-app-back
spec:
  ports:
  - port: 6379
  selector:
    app: mall-app-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-app-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-app-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: mall-app-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: mall-app-front
        image: mall-app-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "mall-app-back"
---
apiVersion: v1
kind: Service
metadata:
  name: mall-app-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mall-app-front
